{{- if and .Values.global.imagePullSecret.create (not .Values.global.imagePullSecret.existingSecret) }}
{{- $registry := .Values.global.imagePullSecret.registry }}
{{- $username := .Values.global.imagePullSecret.username }}
{{- $password := .Values.global.imagePullSecret.password }}
{{- if and .Values.secrets.create .Values.secrets.imagePullSecretRegistry }}
{{- $registry = .Values.secrets.imagePullSecretRegistry }}
{{- end }}
{{- if and .Values.secrets.create .Values.secrets.imagePullSecretUsername }}
{{- $username = .Values.secrets.imagePullSecretUsername }}
{{- end }}
{{- if and .Values.secrets.create .Values.secrets.imagePullSecretPassword }}
{{- $password = .Values.secrets.imagePullSecretPassword }}
{{- end }}
{{- if and $registry $username $password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecret.name | default (printf "%s-imagepullsecret" (include "quackmuzik.fullname" .)) }}
  labels:
    {{- include "quackmuzik.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" (dict "registry" $registry "username" $username "password" $password) }}
---
{{- end }}
{{- end }}

{{- define "imagePullSecret" }}
{{- $auth := printf "%s:%s" .username .password | b64enc }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password $auth | b64enc }}
{{- end }}

