{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quackmuzik.fullname" . }}-secrets
  labels:
    {{- include "quackmuzik.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.discordToken }}
  discord-token: {{ .Values.secrets.discordToken | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.discordClientId }}
  discord-client-id: {{ .Values.secrets.discordClientId | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.lavalinkServerPassword }}
  lavalink-server-password: {{ .Values.secrets.lavalinkServerPassword | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.spotifyClientId }}
  spotify-client-id: {{ .Values.secrets.spotifyClientId | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.spotifyClientSecret }}
  spotify-client-secret: {{ .Values.secrets.spotifyClientSecret | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.appleMusicApiToken }}
  apple-music-api-token: {{ .Values.secrets.appleMusicApiToken | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.deezerMasterKey }}
  deezer-master-key: {{ .Values.secrets.deezerMasterKey | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.yandexMusicToken }}
  yandex-music-token: {{ .Values.secrets.yandexMusicToken | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.vkUserToken }}
  vk-user-token: {{ .Values.secrets.vkUserToken | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tidalToken }}
  tidal-token: {{ .Values.secrets.tidalToken | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tidalRefreshToken }}
  tidal-refresh-token: {{ .Values.secrets.tidalRefreshToken | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.qobuzOauthToken }}
  qobuz-oauth-token: {{ .Values.secrets.qobuzOauthToken | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.qobuzAppId }}
  qobuz-app-id: {{ .Values.secrets.qobuzAppId | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.youtubeOauthRefreshToken }}
  youtube-oauth-refresh-token: {{ .Values.secrets.youtubeOauthRefreshToken | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.sentryDsn }}
  sentry-dsn: {{ .Values.secrets.sentryDsn | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.databasePassword }}
  database-password: {{ .Values.secrets.databasePassword | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.proxyUsername }}
  proxy-username: {{ .Values.secrets.proxyUsername | toString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.proxyPassword }}
  proxy-password: {{ .Values.secrets.proxyPassword | toString | b64enc }}
  {{- end }}
{{- end }}

